### ISSUE TITLE
Use tags over branches

### ISSUE THREAD

**Issue by xeruf** [software-challenge/client-ruby#44]
@jnccd please replace the stale branches by appropriate final-tags with year-prefix, so something like `15.final-packeis` and `22.final-ostseeschach` like in the backend repo

**Comment by xeruf** [comment]
das `.final` sorgt dann auch dafür, dass die sortierung mit bestenden tags hinhaut ;)

**Comment by jnccd** [comment]
Stimmt, was ich vom GitHub Tag Datum her gelesen habe scheint das recht nervig zu steuern sein. Mit `.final` scheint es soweit richtig einsortiert zu sein.
Teils ist das branchende nicht die finale version für das jewailige spiel, aber ich habe die final tags erstmal trotzdem so plaziert wie es im branch war und ich habe teils nicht-spiele-branches mitgenommen.

**Comment by xeruf** [comment]
Frag Sven, der hat die ja alle angelegt, ich habe keine Ahnung ;)
